### ISSUE TITLE
The bridge erc-20 <=> spl is working in one way only

### ISSUE THREAD

**Issue by BornToChop** [certusone/wormhole#207] opened 2021-06-09 18:13 UTC
Hello, 
I converted my $aleph tokens (erc20) into $aleph (spl). But I can not convert them back for two reasons. First, the bridge itself sees only 0.000016 aleph (spl) while I converted 16 thousands $aleph. Second, transaction that should approve the conversion keeps failing all the time.
Here is my eth address: 0x0d9686D3c602a458110F43147bcF33bFc3feF135 (https://etherscan.io/address/0x0d9686d3c602a458110f43147bcf33bfc3fef135)
Here is my solana address: 4wyfVQ6w2Lnv3cdBc4dGpweaWZ7J8UzixWGLgRMX47SK (https://explorer.solana.com/address/4wyfVQ6w2Lnv3cdBc4dGpweaWZ7J8UzixWGLgRMX47SK)

If you need more details let me know or check the 'discussions' section. I described there the process with all details and all possible screenshots

**Comment by leoluk** [comment] 2021-06-11 22:55
Duplicate of https://github.com/certusone/wormhole/discussions/206

We'll take a look!

**Closed by leoluk** 2021-06-11 22:55 UTC
