### ISSUE TITLE
Wormhole WETH sent from Solana to WETH on Ethereum MISSING, data not loading on Recent Transactions

### ISSUE THREAD

**Issue by KikeKewl** [certusone/wormhole#388] opened 2021-09-07 19:57 UTC
I'm trying to complete the transaction from WETH (Solana) to WETH (Ethereum), tried reloading the page but no transaction history appears (it appears loading indefinitely). Please help in completing the transaction.

Transaction:

https://solanabeach.io/transaction/5EH6iQziU4yuJPbF5brBxGEaSoZxur1ii4HXacVCJt9QiwtSkmgA6juYDUYMKS5R7vLB1T2r9hK6gUzXugoAgzDh

**Comment by leoluk** [comment] 2021-09-08 11:24
Duplicate of #274

**Closed by leoluk** 2021-09-08 11:24 UTC
